FROM docker.io/ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

COPY build/silvus-mock /app/silvus-mock
RUN chmod 755 /app/silvus-mock

EXPOSE 8080 50000

ENV SILVUS_MOCK_HTTP_PORT=8080
ENV SILVUS_MOCK_MAINT_PORT=50000

CMD ["/app/silvus-mock"]
